name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.2
      with:
        name: application-go              

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: cabralconsultoria
        password: ${{ secrets.PASS_DOCKER_HUB }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cabralconsultoria/curso_ci-go:${{ github.ref_name }}
                
            
              